name: 'CI/CD for Strapi'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm run build

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
          cd /srv/strapi
          git pull origin main
          npm install
          pm2 restart all
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

