name: Terraform Automated

on:
  push:
    branches:
      - vyankateshwarT  # Triggered on push to main branch

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.7"

      - name: Configure AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.VTAIKAR_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.VTAIKAR_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve || true  # Destroy existing infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy Strapi Application
        run: |
          cd /srv/strapi/
          pm2 delete strapi || true  # Stop existing Strapi process if running
          pm2 start npm --name strapi -- run start
