name: Terraform Manual

on:
  workflow_dispatch:  # Triggered manually

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment:
      AWS_REGION: "us-west-2"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      # Optionally, include steps for validating or other pre-apply checks

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve

      # Add more steps as needed (e.g., outputs, notifications)
