name: Deploy Strapi Application

on:
  push:
    branches:
      - Parameswaran
  pull_request:
    branches:
      - Parameswaran

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: SSH into EC2 instance and deploy Strapi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}  # Ensure this is set in your GitHub Secrets
        username: ubuntu
        key: ${{ secrets.PRIVATE_SSH_KEY }}  # Ensure this is set in your GitHub Secrets
        script: |
          cd /srv/strapi
          sudo git pull origin Parameswaran
          sudo npm install
          # Check if Strapi is already managed by pm2
          if ! sudo pm2 status | grep -q "strapi-app"; then
            echo "Strapi is not managed by pm2. Starting Strapi with pm2..."
            sudo pm2 start "npm run start --silent" --name "strapi-app"
          else
            echo "Strapi is already managed by pm2. Restarting Strapi..."
            sudo pm2 restart strapi-app
          fi
