name: Terraform_Manual

on: workflow_dispatch  # To enable a workflow to be triggered manually, 
                       # you need to configure the "workflow_dispatch" event.
jobs: 
  Terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # env:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: terraform
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7" 
          terraform_wrapper: false

      - name: Configure AWS Credentials
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "AWS credentials configured"
           
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform/user_data_strapi.sh
        run: terraform plan -no-color

      - name: Terraform Apply
        
        run: terraform apply -auto-approve
      
      - name: Terraform destroy
        run: terraform destroy -auto-approve    
            
