name: Terraform Deployment

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.KARTIK_BAWANE_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.KARTIK_BAWANE_SECRET_KEY }}  

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: strapi-project/terraform-files
 
      - name: Terraform Apply
        run: terraform destroy -auto-approve
        working-directory: strapi-project/terraform-files

      - name: Store Instance IP 
        run: echo $(terraform output instance_ip) > strapi-project/instance_ip.txt
        working-directory: strapi-project/terraform-files

      - name: Display Instance IP
        run: cat strapi-project/terraform-files/instance_ip.txt

